### ISSUE TITLE
Frame_id of camera info is empty

### ISSUE THREAD

**Issue by Tacha-S** [microsoft/Azure_Kinect_ROS_Driver#218]
**Describe the bug**
The frame of the camera information that I calibrated myself is empty.

**To Reproduce**
1. Calibrate azure kinect.
2. Save calibration parameter to `~/.ros/camera_info/azure_kinect_rgb_*_720P.yaml`
3. Launch with the calibration parameter.
4. Echo camera info topic.

**Expected behavior**
Set frame_id from `calibration_data_`.

**Logs**
```
header: 
  seq: 0
  stamp: 
    secs: 1634000292
    nsecs: 678471820
  frame_id: ""
height: 720
width: 1280
distortion_model: "plumb_bob"
D: [0.0817770987146689, -0.03863133970336082, -0.002815680391212852, 0.001033577331441764, 0.0]
K: [622.1709492000613, 0.0, 643.0973571702241, 0.0, 621.4689043778138, 364.8296932052655, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [650.3511352539062, 0.0, 645.14253979977, 0.0, 0.0, 649.095703125, 361.8063628262607, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
---
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04
